<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog [
        <!ELEMENT catalog (book*)>
        <!ELEMENT book (author, title, genre, price, publish_date, description)>
        <!ATTLIST book id CDATA #REQUIRED>
        <!ELEMENT author (#PCDATA)>
        <!ELEMENT title (#PCDATA)>
        <!ELEMENT genre (#PCDATA)>
        <!ELEMENT price (#PCDATA)>
        <!ELEMENT publish_date (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        ]>
<catalog>
    <book id="bk101">
        <author>Gambardella, Matthew</author>
        <title>XML Developer's Guide</title>
        <genre>Computer</genre>
        <price>44.95</price>
        <publish_date>2000-10-01</publish_date>
        <description>An in-depth look at creating applications with XML.</description>
    </book>
    <book id="bk102">
        <author>Ralls, Kim</author>
        <title>Midnight Rain</title>
        <genre>Fantasy</genre>
        <price>5.95</price>
        <publish_date>2000-12-16</publish_date>
        <description>A former architect battles corporate zombies, an evil sorceress, and her own childhood to become queen of the world.</description>
    </book>
</catalog>
